name: Publish Docker Image

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set Docker Image Tag
        id: set_tag
        run: |
          if [ "$GITHUB_REF" = "refs/heads/main" ]; then
            echo "TAG=latest" >> $GITHUB_ENV
          elif [ "$GITHUB_REF" = "refs/heads/dev" ]; then
            echo "TAG=dev" >> $GITHUB_ENV
          fi
      - name: Build Docker Image
        uses: docker/build-push-action@v5.1.0
        with:
          pull: true
          push: true
          tags: mrshandy/zephyrzen:${{ env.TAG }}
